tasks:
  loadEnvironment:
    name: Initialize
    description: Init the environment
    triggeredBy:
      - postEnvironmentStart
    command: |
      cp .env.example .env &&
      # sed -i "s#APP_URL=http://localhost#APP_URL=$(gp url 8000)#g" .env
      # sed -i "s#GITPOD_VITE_URL=#GITPOD_VITE_URL=$(gp url 5173)#g" .env
      touch database/database.sqlite
      composer install --ignore-platform-reqs
      # php artisan key:generate
      # php artisan storage:link
      # php artisan migrate --seed
      # php artisan db:seed --class=TodoSeeder
      # php artisan serve
