tasks:
  copyEnv:
    name: Copy Environment
    description: Creates the .env file
    triggeredBy:
      - postEnvironmentStart
    command: cp .env.example .env

  phpOperations:
    name: Setup PHP and Run
    dependsOn: ["copyEnv"]
    triggeredBy:
      - postEnvironmentStart
    command: |
      composer install --ignore-platform-reqs

      sed -i "s#APP_URL=http://localhost#APP_URL=$(gp url 8000)#g" .env
      sed -i "s#GITPOD_VITE_URL=#GITPOD_VITE_URL=$(gp url 5173)#g" .env

      touch database/database.sqlite

      php artisan key:generate
      php artisan storage:link
      php artisan migrate --seed
      php artisan db:seed --class=TodoSeeder
      php artisan serve
